version: 0.0
os: linux
files:
  - source: /        # Copy everything from the root of your repo
    destination: /home/ec2-user/app # Directory on the EC2 instance

hooks:
  BeforeInstall:
    - location: scripts/run_docker.sh
      timeout: 300
      runas: ec2-user

