version: 0.2

phases:
  install:
    commands:
      - echo Using Docker preinstalled in CodeBuild image

  build:
    commands:
      - echo Running ZAP scan in Docker...
      - docker run --rm -v $(pwd):/zap/wrk/:rw zaproxy/zap-stable zap.sh -cmd -quickurl http://16.170.246.106:3001 -quickout /zap/wrk//zap/wrk/reports/zap/zap_report.html -quickprogress

  post_build:
    commands:
      - echo ZAP scan completed
      - echo Uploading ZAP report to S3...
      - aws s3 cp reports/zap/zap_report.html s3://codepipelinestartertempla-codepipelineartifactsbuc-v8bguamqaest/DAST_logs/zap_report.html

artifacts:
  files:
    - zap_report.html
version: 0.2

phases:
  build:
    commands:
      # - echo "Hello World"
