version: 0.2

phases:
  install:
    commands:
      - echo Using Docker preinstalled in CodeBuild image

  build:
    commands:
      - echo Running ZAP scan in Docker...
      - docker run --rm -v $(pwd):/zap/wrk/:rw ghcr.io/zaproxy/zap-full-scan -t http://16.170.246.106:3001 -r zap_report.html

  post_build:
    commands:
      - echo ZAP scan completed
      - echo Uploading ZAP report to S3...
      - |
        if [ -f zap_report.html ]; then
          aws s3 cp zap_report.html s3://codepipelinestartertempla-codepipelineartifactsbuc-v8bguamqaest/DAST_logs/zap_report.html
        else
          echo "ZAP report not found — skipping upload."
        fi

artifacts:
  files:
    - zap_report.html
